spring.application.name=pepclass
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.data.mongodb.uri=mongodb://localhost:27017/pepclass
spring.data.mongodb.auto-index-creation=true
